#开发环境相关配置:
#1、Spring相关配置
spring:
  #1.1、数据源配置(mamabike密码为空,duyang_bike密码为root)
  datasource:
     name: dev
     #url: jdbc:mysql://localhost:3306/mamabike
     url: jdbc:mysql://localhost:3306/duyang_bike
     username: root
     password: root

  #1.2、ActiveMQ消息队列配置
#  activemq:
#      broker-url: tcp://localhost:61616
#      #pool enabled 默认就是false,不写也可以
#      pool:
#        enabled: false

#2、Redis相关配置
redis:
    host: 127.0.0.1
    port: 6379
    #auth密码和redis.config设置的密码保持一致
    auth: duyang001
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000


#springdata
  data:
    mongodb:
      uri: mongodb://localhost:27017/mama-bike

